### ISSUE TITLE
Failed at make install due to udp_tunnel - Bringing from the old repo

### ISSUE THREAD

**Issue by devappforthebest** [free5gc/gtp5g#1]
Currently, I'm try to install modules after already building. When running ```make install``` as root (inside a **docker** - building image process ), I get the following error:

```
modprobe udp_tunnel
modprobe: FATAL: Module udp_tunnel not found in directory 
/lib/modules/5.4.0-77-generic
make: *** [Makefile:20: install] Error 1
```

Could you share with me how to fix this error? (install udp_tunnel module)

**Comment by muthuramanecs03g** [comment]
Hi @devappforthebest,

The udp_tunnel will be located in the following location, if you are not able to find then download the linux kernel source code like your kernel version, and then build that source. Finally, install the udp_tunnel after that gtp5g.ko.

filename:       /lib/modules/5.4.0-54-generic/kernel/net/ipv4/udp_tunnel.ko
license:        GPL
srcversion:     0A315BA6124B0664F4D23FB
depends:        
retpoline:      Y
intree:         Y
name:           udp_tunnel
vermagic:       5.4.0-54-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4

**Comment by gzzx2021** [comment]
HI,I find this issue too,could you share more details of the solution.
