### ISSUE TITLE
Sometimes GTP5g Module is not loaded post VM reboot

### ISSUE THREAD

**Issue by aleemgsl** [free5gc/gtp5g#122]
Hi Team,

I have installed gtp5g v0.8.10. Free5gc UPF is up and running and processing data packets. When my machine is rebooting, UPF does not come up. And to make it up, I need to re-install gtp5g module. 

lsmod | grep gtp5 does not show any module. 

This issue is intermittent. But its affecting traffic when it occurs and UPF does not get started automatically.

Can someone help resolving this issue?

**Comment by aleemgsl** [comment]
@free5gc-org can you please look into this?

**Comment by andy89923** [comment]
Hi @aleemgsl ,

The #121 should solved the problem!

**Comment by amanThakral002** [comment]
Hi, even after adding the changes in #121 , I am still getting issue with module not loaded post reboot.
