### ISSUE TITLE
Support for QER QoS

### ISSUE THREAD

**Issue by aviweit** [free5gc/gtp5g#2]
Hi,

I have opened an issue related to "Invalid extension header length" when passing qer definition earlier this year (https://github.com/PrinzOwO/gtp5g/issues/27).

Re-testing with the latest version of gtp5g and libgtp5gnl in free5gc, I do not get this error anymore and ping succeeds for me.

However, I was told that QoS is not supported yet at that time (https://github.com/PrinzOwO/gtp5g/issues/27#issuecomment-840592390).

I would like to ask whether such a support had been added and if not, when is it planned to be?

I am asking this because we have set up a local free5gc with UERANSIM deployment and would like to create pdu sessions from  slices with different QoS.

Thanks.

**Comment by muthuramanecs03g** [comment]
Hi @aviweit,

We didn't implement QoS part in gtp5g.

I like to update you about free5GC/upf and gtp5g. The kernel module gtp5g can handle the GTP-U extension header like PDU Session Container(0x85). It can decap and encap the GTP-U header along with extension header type 0x85. But, some limitations:

1) upf can send atmost only one QER to gtp5g

2) gtp5g didn't do traffic policy or shaping based on QER, and only for decap and encap.

Currently, we don't have any plan for QoS support and like to do based on RFC2698. 

If you are interested to implement that part then please let me know.

For your reference,
> RFC2698 implementation p4lang/behavioral-model/src/bm_sim/meters.cpp. 
> Spec https://www.rfc-editor.org/rfc/pdfrfc/rfc2698.txt.pdf

**Comment by aviweit** [comment]
Hi @muthuramanecs03g ,

Thank you for the helpful response.
