### ISSUE TITLE
Regression by code splitting

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/gtp5g#34]
Due to the code split done in https://github.com/free5gc/gtp5g/commit/f545b8c6dac24ae2ae206f7003b49a3c70d1047c, for example, the existing fix is lost, such as in 84c3c0ba.

**Comment by free5gc-org** [comment]
@ShouheiNishi 

Thanks for the notification.
Already patched in https://github.com/free5gc/gtp5g/pull/42
This PR includes https://github.com/free5gc/gtp5g/commit/84c3c0bae543b0adc689fc6f6a2a6f6383fd1696 and https://github.com/free5gc/gtp5g/commit/dc650e8e8de65dda24563f072cafa660a2c9b5c2.
Please check it.
