### ISSUE TITLE
 fatal error: stdbool.h: No such file or directory

### ISSUE THREAD

**Issue by kimsame** [free5gc/gtp5g#43]
make -C /lib/modules/5.18.13-200.fc36.x86_64/build M=/root/gtp5g  modules
make[1]: Entering directory '/usr/src/kernels/5.18.13-200.fc36.x86_64'
  CC [M]  /root/gtp5g/main.o
  CC [M]  /root/gtp5g/api_version.o
/root/gtp5g/api_version.c:1:10: fatal error: stdbool.h: No such file or directory
    1 | #include <stdbool.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:289: /root/gtp5g/api_version.o] Error 1
make[1]: *** [Makefile:1842: /root/gtp5g] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.18.13-200.fc36.x86_64'
make: *** [Makefile:50: module] Error 2

**Comment by free5gc-org** [comment]
fixed in https://github.com/free5gc/gtp5g/pull/44
