### ISSUE TITLE
compilation error In function ‘gtp5g_encap_enable’

### ISSUE THREAD

**Issue by theevilcat** [free5gc/gtp5g#45]
Hello, I am trying to compile on my system, but it throws an error.
I cloned the v0.6.2 of the repository:
`git clone -b v0.6.2 https://github.com/free5gc/gtp5g.git`

Characteristics of the system:
`ubuntu@testfree5gcallinone:~/gtp5g$ uname -r`
`4.15.0-20-generic`
`ubuntu@testfree5gcallinone:~/gtp5g$ lsb_release -a`
`No LSB modules are available.`
`Distributor ID: Ubuntu`
`Description:    Ubuntu 18.04 LTS`
`Release:        18.04`
`Codename:       bionic`
`ubuntu@testfree5gcallinone:~/gtp5g$ gcc --version`
`gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`

![Screenshot 2022-08-03 090112](https://user-images.githubusercontent.com/10691629/182614273-f862d846-639d-4097-853f-1a88bb5f56d7.png)

Thank you for your help

**Comment by chen042531** [comment]
Maybe, you can update your linux kernel.
I update my kernel use commands below.
```
sudo apt update
sudo apt-get install linux-image-5.15.0-41-generic
sudo apt-get install linux-headers-5.15.0-41-generic
sudo apt-get install linux-modules-5.15.0-41-generic
sudo apt-get install linux-modules-extra-5.15.0-41-generic
sudo update-initramfs -u -k all
sudo update-grub
```

**Comment by tim-ywliu** [comment]
@theevilcat 

Your kernel version is too old.
Please run upgrade your kernel version 5.0.0-23-generic, 5.4.x or 5.8.x.
