### ISSUE TITLE
encap.c error

### ISSUE THREAD

**Issue by kiufta** [free5gc/gtp5g#50]
This happens when I try to compile 0.6.6 with gcc 12.2. Sorry, but LC_ALL=C got ignored:
```
./gtp5g/encap.c: In Funktion »gtp5g_fwd_skb_encap«:
./gtp5g/encap.c:512:22: Fehler: Argument falschen Typs für Inkrementierung
  512 |     stats->rx_packets++;
      |                      ^~
./gtp5g/encap.c:513:21: Fehler: Ungültige Operanden für binäres + (haben »u64_stats_t« und »unsigned int«)
  513 |     stats->rx_bytes += skb->len;
      |     ~~~~~~~~~~~~~~~ ^~ ~~~~~~~~
      |          |                |
      |          u64_stats_t      unsigned int
make[2]: *** [scripts/Makefile.build:249: ./gtp5g/encap.o] Fehler 1

```

**Comment by kiufta** [comment]
English version:
```
./gtp5g/encap.c: In function ‘gtp5g_fwd_skb_encap’:
./gtp5g/encap.c:512:22: error: wrong type argument to increment
  512 |     stats->rx_packets++;
      |                      ^~
./gtp5g/encap.c:513:21: error: invalid operands to binary + (have ‘u64_stats_t’ and ‘unsigned int’)
  513 |     stats->rx_bytes += skb->len;
      |     ~~~~~~~~~~~~~~~ ^~ ~~~~~~~~
      |          |                |
      |          u64_stats_t      unsigned int
```
@Roy-Hu Is your branch fixing this issue?

**Comment by Roy-Hu** [comment]
Hi, I have compiled 0.6.6 with gcc 12.2.0 and it works correctly, can you provide me more of your setting for debugging?

> English version:
> 
> ```
> ./gtp5g/encap.c: In function ‘gtp5g_fwd_skb_encap’:
> ./gtp5g/encap.c:512:22: error: wrong type argument to increment
>   512 |     stats->rx_packets++;
>       |                      ^~
> ./gtp5g/encap.c:513:21: error: invalid operands to binary + (have ‘u64_stats_t’ and ‘unsigned int’)
>   513 |     stats->rx_bytes += skb->len;
>       |     ~~~~~~~~~~~~~~~ ^~ ~~~~~~~~
>       |          |                |
>       |          u64_stats_t      unsigned int
> ```
> 
> @Roy-Hu Is your branch fixing this issue?

**Comment by kiufta** [comment]
@Roy-Hu Which kernel version do you use? I'm currently on 6.0, but the switch to 64-bit RX/TX statistics is already a few versions old.

**Comment by tim-ywliu** [comment]
@kiufta 

Due to the evolution of Linux kernel, this module would not work with every kernel version. Please run this module with kernel version 5.0.0-23-generic, 5.4.x or 5.8.x.

**Comment by a-andre** [comment]
The compile error can be fixed with:
```diff
---- a/src/gtpu/encap.c
+++ b/src/gtpu/encap.c
@@ -756,8 +756,8 @@ static int gtp5g_fwd_skb_encap(struct sk_buff *skb, struct net_device *dev,
 
     stats = this_cpu_ptr(skb->dev->tstats);
     u64_stats_update_begin(&stats->syncp);
-    stats->rx_packets++;
-    stats->rx_bytes += skb->len;
+    u64_stats_inc(&stats->rx_packets);
+    u64_stats_add(&stats->rx_bytes, skb->len);
     u64_stats_update_end(&stats->syncp);
 
     pdr->ul_pkt_cnt++;
```

Kernel commit adding these functions: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=316580b69d0a7aeeee5063af47438b626bc47cbd

**Comment by tim-ywliu** [comment]
fixed in https://github.com/free5gc/gtp5g/pull/61
