### ISSUE TITLE
gtp5g_handle_skb_ipv4 error

### ISSUE THREAD

**Issue by balti09** [free5gc/gtp5g#71]
i'm getting this error from the kernel messages :
![image](https://user-images.githubusercontent.com/72893228/228466637-3c158928-2cfe-44ee-b850-0cc5357ec999.png)

i'm installing gtp5g kernel module in order to test free5gc but when UPF pod is up and running i got  errors in upfgtp interface and when UE's ping requests througth uesimtun0 interface, it reach the destination but responses cannot reach the UEs. 
my host os: ubuntu 20.04
kernel version : 5.4.0-1101-gcp

**Comment by tim-ywliu** [comment]
fixed in https://github.com/free5gc/gtp5g/pull/72
