### ISSUE TITLE
kernel crash when I generated a lot of traffic

### ISSUE THREAD

**Issue by K-Nanako** [free5gc/gtp5g#9]
Hello.

I am using gtp5g v0.4.0 with [free5gc-compose](https://github.com/free5gc/free5gc-compose).

On the performance measurement test, when I generated a lot of traffic, the kernel crash was happened and the host OS was often goes down.

As you can see in the kernel log I attached below, there are some errors related to gtp5g kernel module.
[log.txt](https://github.com/free5gc/gtp5g/files/7723675/log.txt)

I think this could be a gtp5g issue.  I suspect the cause is probably in kfree_skb.
Do you have any information about this issue?

The environment which I'm using is below.
- I'm using the kernel version of 5.0.0-23-generic.
- I'm using UERANSIM as gNB and UE. These are deployed on virtual machine of KVM on the same machine.

Incidentally, I tried to use gtp5g v0.4.1, but it couldn't work normally. So I use the version of 0.4.0.

Thank you for your help.

**Comment by muthuramanecs03g** [comment]
@K-Nanako,

I suspect, this issue may happened due to improper skb header initialization at the time of kfree_skb(), because we add more header fields in the path of processing.

From your log, the call flow: gtp5g_encap_recv -> gtp1u_udp_encap_recv -> gtp5g_rx -> gtp5g_fwd_skb_encap ->ip_xmit -> ip_local_out

The proper header initialization like below and also make sure the skb headers are properly set prior to the call of free_skb()

   > /* Now that the UDP and the GTP header have been removed, set up the
   > * new network header. This is required by the upper layer to
   >  * calculate the transport header.
   > * */
   > skb_reset_network_header(skb);

We are not able to reproduce this issue at our side, we need your help to fix the problem by tracing the code like above.

**Comment by K-Nanako** [comment]
Hello @muthuramanecs03g ,

Thank you for your investigation.

I'm so sorry, but I'm not familiar with this area. So could you give me some advices to trace the code?

> The proper header initialization like below and also make sure the skb headers are properly set prior to the call of free_skb()

Do you mean that I should add the code to print the value of skb in gtp5g.c?


I'd like to add some information about the situation for this issue.

- I'm using gtp5g v0.4.0 and haven't changed the original code.
- The kernel crash often occur when sending packets by using iperf command, and in many cases, kernel crash was happened when I execute iperf client without starting iperf server. (However, it did not always happen.)
`iperf -c <ip address> -u -e -B 60.60.0.1 -l 1470 -b 1000M`
- The iperf server and iperf client (UERANSIM UE) are running on different VMs in the same host.
- The free5gc  is running in a container within the same host.

I appreciate for your help.

**Comment by K-Nanako** [comment]
Hello,

Is there a possibility double freeing memory is causing a problem?
Suppose the memory was released by kernel process before `kfree_skb ()` on line 2210 (for example, a drop according to the iptables rule), will the memory release in gtp5g be a double freeing memory ?
Therefore , I was wondering if the kfree_skb ()  nessesary on line 2210 or not.
Anyway , I'm still trying to find a way to constantly reproduce this issue .
I'm so sorry if it is my misunderstanding.

Thank you for your corporation.

**Comment by muthuramanecs03g** [comment]
Hi @K-Nanako,

Can you replace as dev_kfree_skb() instead of kfree_skb() in function 
> static int gtp5g_encap_recv(struct sock *sk, struct sk_buff *skb)
> case -1:
        GTP5G_ERR(gtp->dev, "GTP packet has been dropped\n");
        kfree_skb(skb);
        ret = 0;
        break;
    }

Like 
> case -1:
        GTP5G_ERR(gtp->dev, "GTP packet has been dropped\n");
        dev_kfree_skb(skb);
        ret = 0;
        break;
    }

**Comment by K-Nanako** [comment]
Hello @muthuramanecs03g 

Thank you for your advice.
I replaced the code to dev_kfree_skb() from kfree_skb() as you mentioned.
Unfortunately, the kernel crash happened again.

This time since I've set the slub debugging option, I was able to get additional information like below in crash log.
"Poison overwritten" seems like a message appeals when double freeing memory occur.
 So, I'm thinking of further investigation on this point.

```
[60348.998236] upfgtp:[gtp5g] gtp5g_encap_recv: GTP packet has been dropped
[60348.998305] =============================================================================
[60348.998308] BUG skbuff_head_cache (Tainted: G    B      OE    ): Poison overwritten
[60348.998309] ----------------------------------------------------------------------------- 
```
Thank you for your corporation.

**Comment by K-Nanako** [comment]
Hello @muthuramanecs03g ,

According to the logs, it seems double memory freeing is occurring.
When memory release was executed from ip_xmit's ip_local_out, gtp5g.c's kfree_skb() in line 2210 seems to be causing double memory freeing.

I would be appreciated it if you could confirm this point.

**Comment by chen042531** [comment]
![image](https://user-images.githubusercontent.com/9147191/200986038-cdebf1fa-6a6c-4601-881b-1d6649925cb2.png)

I try "iperf -c <ip address> -u -e -B 60.60.0.1 -l 1470 -b 1000M" 10 times with free5gc(v3.2.1) and gtp5g(v0.6.7), there is no panic.
Maybe you can try  gtp5g(v0.6.7)

**Comment by K-Nanako** [comment]
Hello all,
Thank you for your replies. 

We have now upgraded to later versions and have not experienced the kernel crash issue that we previously encountered. 
Therefore, I believe this issue should be closed. 

I apologize for keeping this issue open for an extended period of time.
Thank you for your support.
